TCP:
  host: localhost
  port: 54333
  buffer_size: 8388608 # 8MB
  timeout: 10 # seconds

logging:
  level: info
  directory: null
  formatter: '%(asctime)s - %(name)s - %(levelname)s | %(message)s'

data:
  data_dir: F:\data\ARPESdatabase\maps\SGM4
  file_name: MBT_C_62 # Z006_35_0.h5
  target_dir: C:\Users\stein\OneDrive\Documents\_Work\_code\ARPES-ASTRID\smartscan\data

scan:
  save_to_file: false
  simulate_times: True
  # dwell_time: 0.1 # seconds